#!/bin/bash
RED='\e[31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'                                                
NC='\033[0m' # Sem cor
                                                                  # Exibe o prompt para inserir o alvo
echo -e "       ${CYAN}Insira o alvo:   ${NC}"
# Lê a entrada do usuário para o alvo
read ALVO
                                                                  # Verifique se a entrada contém apenas números e caracteres especiais                                          
 if [[ ! "$ALVO" =~ ^[0-9[:punct:]]+$ ]]; then
echo "  "
        echo -e "${RED}A entrada deve conter apenas números | formato: 127.0.0.1${NC}"
        exit -1
    fi

#Saida de Arquivo

saida=".infscan.txt"

#Limpa os antigo
clear

#escolha

while true; do
echo "        ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒"
echo "        ▒▒▒▒▒▒▒▒▄▄▄▄▄▄▄▄▒▒▒▒▒▒"
echo "        ▒▒█▒▒▒▄██████████▄▒▒▒▒"
echo "        ▒█▐▒▒▒████████████▒▒▒▒"
echo "        ▒▌▐▒▒██▄▀██████▀▄██▒▒▒"
echo "        ▐┼▐▒▒██▄▄▄▄██▄▄▄▄██▒▒▒"
echo "        ▐┼▐▒▒██████████████▒▒▒"
echo "        ▐▄▐████─▀▐▐▀█─█─▌▐██▄▒"
echo "        ▒▒█████──────────▐███▌"
echo "        ▒▒█▀▀██▄█─▄───▐─▄███▀▒"
echo "        ▒▒█▒▒███████▄██████▒▒▒"
echo "        ▒▒▒▒▒██████████████▒▒▒"
echo "        ▒▒▒▒▒██████████████▒▒▒"
echo "        ▒▒▒▒▒█████████▐▌██▌▒▒▒"
echo "        ▒▒▒▒▒▐▀▐▒▌▀█▀▒▐▒█▒▒▒▒▒"
echo "        ▒▒▒▒▒▒▒▒▒▒▒▐▒▒▒▒▌▒▒▒▒▒"
echo "        ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒"
echo " "
echo " "
        echo -e "       ${CYAN}Menu - ByteBandits Inc.${NC}"
        echo ""
        echo "1) Scan normal"
        echo "2) Scan agressivo"
        echo "3) Scan porta especifica"
        echo "99) Sair"
        echo ""
        read escolha
        clear
        case "$escolha" in

        1)

        clear

                # Function Loading
        SPINNER="/-\|"

        # Define o tempo de espera entre cada quadro (em segundos)
        DELAY=0.1

        # Inicia a animação de carregamento em segundo plano
        animate_loading() {
            while :; do
                for i in $(seq 0 3); do
                    echo -ne "\r[${SPINNER:$i:1}] Carregando..."
                    sleep $DELAY
                done
            done
        }

        # Inicia a animação de carregamento em segundo plano
        animate_loading &

        # Armazena o PID da animação de carregamento
        ANIMATION_PID=$!

        # Seu código de escaneamento aqui
        nmap -T4 -F -Pn $ALVO > $saida

        # Aguarde um tempo (simulação)
        sleep 5

        # Pare o carregamento
        kill $!

        clear
        echo -e "${GREEN}  - Alvo: ${ALVO}${NC}"
        echo "  "
        cat $saida
        echo "  "
        echo -e "${CYAN} Escaneamento concluido!"
        break
        ;;

        2)

        clear
                # Function Loading
        SPINNER="/-\|"

        # Define o tempo de espera entre cada quadro (em segundos)
        DELAY=0.1

        # Inicia a animação de carregamento em segundo plano
        animate_loading() {
            while :; do
                for i in $(seq 0 3); do
                    echo -ne "\r[${SPINNER:$i:1}] Carregando..."
                    sleep $DELAY
                done
            done
        }

        # Inicia a animação de carregamento em segundo plano
        animate_loading &

        # Armazena o PID da animação de carregamento
        ANIMATION_PID=$!

        # Seu código de escaneamento aqui
        nmap -Pn -A -T4 -p- -v $ALVO > $saida

        # Aguarde um tempo (simulação)
        sleep 5

        # Pare o carregamento
        kill $!

        clear
        echo -e "${GREEN}  - Alvo: ${ALVO}${NC}"
        echo "  "
        cat $saida
        echo "  "
        echo -e "${CYAN} Escaneamento concluido!"
        break
        ;;

        3)

        echo -e "       ${CYAN}Insira a Porta: ${NC}"
                                                        # Lê a entrada do usuário para o alvo
        read PORTA

        # Verifique se a entrada contém apenas números
        if [[ ! "$PORTA" =~ ^[0-9]+$ ]]; then
    echo -e "${RED}A entrada deve conter apenas números.${NC}"
        exit -1
fi

        clear
                # Function Loading
        SPINNER="/-\|"

        # Define o tempo de espera entre cada quadro (em segundos)
        DELAY=0.1

        # Inicia a animação de carregamento em segundo plano
        animate_loading() {
            while :; do
                for i in $(seq 0 3); do
                    echo -ne "\r[${SPINNER:$i:1}] Carregando..."
                    sleep $DELAY
                done
            done
        }

        # Inicia a animação de carregamento em segundo plano
        animate_loading &

        # Armazena o PID da animação de carregamento
        ANIMATION_PID=$!

        # Seu código de escaneamento aqui
        nmap -T4 -p${PORTA} -Pn $ALVO > $saida

        # Aguarde um tempo (simulação)
        sleep 5

        # Pare o carregamento
        kill $!

        clear
        echo -e "${GREEN}  - Alvo: ${ALVO}${NC}"
        echo "  "
        cat $saida
        echo "  "
        echo -e "${CYAN} Escaneamento concluido!"
        break
        ;;

        99)
        break
        ;;

esac
done
